apiVersion: apps/v1
kind: Deployment
metadata:
  name: coffee-api
  labels:
    app: coffee-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coffee-api
  template:
    metadata:
      name: coffee-api
      labels:
        app: coffee-api
    spec:
      containers:
        - name: coffee-api
          # TODO build with random tags
          image: coffee-shop-api:latest
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      