# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

    (1..1).each do |i|
        config.vm.define "worker-node-#{i}" do |node|
          node.vm.box = "hashicorp/bionic64"
          node.vm.box_version = "1.0.282"
          node.vm.hostname = "node-#{i}"

          node.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
            vb.cpus = "1"
            vb.name = "worker-node-#{i}"
          end
        end
    end
end
